apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sdo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sdo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sdo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.leaderElection.enabled }}
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:8081
            {{- if .Values.aws.region }}
            - --aws-region={{ .Values.aws.region }}
            {{- end }}
          env:
            {{- if .Values.aws.region }}
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            - name: probes
              containerPort: 8081
          livenessProbe:
            httpGet: { path: /healthz, port: probes }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /readyz, port: probes }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
