---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-distribution-operator
  namespace: secret-distribution-operator
  annotations:
    # This annotation must be overridden per-cluster with the real IRSA role ARN.
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/secret-distribution-operator
