//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// This file is a placeholder; the real file is produced by `make generate`
// (which runs `controller-gen object`). It is committed empty-of-content
// so that the package compiles in environments that haven't run codegen yet.
//
// Run: make generate
//
// to regenerate the actual DeepCopy and DeepCopyInto methods for each
// type in this package.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies into out.
func (in *ExportSecret) DeepCopyInto(out *ExportSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a new copy of the receiver.
func (in *ExportSecret) DeepCopy() *ExportSecret {
	if in == nil {
		return nil
	}
	out := new(ExportSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ExportSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ExportSecretSpec) DeepCopyInto(out *ExportSecretSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *ExportSecretSpec) DeepCopy() *ExportSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ExportSecretSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExportSecretStatus) DeepCopyInto(out *ExportSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedTime != nil {
		in, out := &in.LastSyncedTime, &out.LastSyncedTime
		*out = (*in).DeepCopy()
	}
}

func (in *ExportSecretStatus) DeepCopy() *ExportSecretStatus {
	if in == nil {
		return nil
	}
	out := new(ExportSecretStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ExportSecretList) DeepCopyInto(out *ExportSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExportSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ExportSecretList) DeepCopy() *ExportSecretList {
	if in == nil {
		return nil
	}
	out := new(ExportSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *ExportSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ImportSecret) DeepCopyInto(out *ImportSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ImportSecret) DeepCopy() *ImportSecret {
	if in == nil {
		return nil
	}
	out := new(ImportSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *ImportSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ImportSecretSpec) DeepCopyInto(out *ImportSecretSpec) { *out = *in }

func (in *ImportSecretSpec) DeepCopy() *ImportSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ImportSecretSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ImportSecretStatus) DeepCopyInto(out *ImportSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedTime != nil {
		in, out := &in.LastSyncedTime, &out.LastSyncedTime
		*out = (*in).DeepCopy()
	}
}

func (in *ImportSecretStatus) DeepCopy() *ImportSecretStatus {
	if in == nil {
		return nil
	}
	out := new(ImportSecretStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ImportSecretList) DeepCopyInto(out *ImportSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImportSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ImportSecretList) DeepCopy() *ImportSecretList {
	if in == nil {
		return nil
	}
	out := new(ImportSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *ImportSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
